dist: xenial
sudo: required
language: java
jdk:
  - openjdk8
env:
  global:
    - BUILD_PATH=docs
script:
  - JAVA_HOME_OVERRIDE=$JAVA_HOME ./build-docs.sh
deploy:
  provider: pages
  local-dir: $BUILD_PATH
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: add-travis
  edge:
    branch: v1.8.47
